@startuml component diagram
!includeurl style/style.pu
skinparam Nodesep 10
' skinparam ranksep 20

title Trafic control system:\nComponent Diagram


' Components
component configurator
component TrafficController
component TrafficLight

' relationships between the components.
configurator --> TrafficController : configures
configurator --> TrafficController : starts
TrafficController --> TrafficController : ack-noack\ntraffic controller state
TrafficController --> TrafficLight : sends commands


@enduml