@startuml component diagram
!includeurl style/style.pu
skinparam Nodesep 10
skinparam ranksep 20

title Trafic control system: Component Diagram


' Components
component configurator
component ampleEngine
component ampleLights

' relationships between the components.
configurator --> ampleEngine : configures
configurator --> ampleEngine : starts
ampleEngine --> ampleEngine : interacts with
ampleEngine --> ampleLights : sends commands


@enduml