@startuml context diagram (ES view)
!include <c4/C4_Context.puml>  

'ref http://plantuml.com/stdlib
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

!includeurl style/style.pu
skinparam Nodesep 70
skinparam ranksep 30

title Traffic control system\nContext Diagram (ES view)


storage "**Master**" as Master #white;line.dashed;line:darkgrey;
storage "**Slave**" as Slave #white;line.dashed;line:darkgrey;


' Terminals
node TrafficLightEast  {
  Rectangle "Red LED" as RedLed1 
  Rectangle "Orange LED" as OrangeLed1
  Rectangle "Green LED" as GreenLed1
  RedLed1 --[hidden]> OrangeLed1
  OrangeLed1 --[hidden]> GreenLed1
}

node TrafficLightWest  {
  Rectangle "Red LED" as RedLed2
  Rectangle "Orange LED" as OrangeLed2
  Rectangle "Green LED" as GreenLed2
  RedLed2 --[hidden]> OrangeLed2
  OrangeLed2 --[hidden]> GreenLed2

}


' relationships between the terminals and the system.

Master --> Slave : STOP, TRANSITION, GO, WARNING
Slave --> Master : ACK, NACK, HARTBEAT?
Slave --> TrafficLightEast : RED:on, RED:off, ORANGE:on, ORANGE:off, ORANGE:blinking, GREEN:on, GREEN:off
Master --> TrafficLightWest : RED:on, RED:off, ORANGE:on, ORANGE:off, ORANGE:blinking, GREEN:on, GREEN:off

@enduml