@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' default header Property, Value
Title Traffic controll deployment diagram

Deployment_Node_L(arduino1, "Arduino 1") {
    Container(master, "Master East", "Compiled sketch"){
    Node(traficController, "TraficController", "Component")
    Node(traficLightEast, "TraficLight East", "Component")
}
}

Deployment_Node_R(arduino2, "Arduino 2") {
    Container(traficLightWest, "TraficLight West", "Compiled sketch")
}


' relations
Rel_R(traficController, traficLightWest, "Messages", "Serial Protol")
Rel_L(traficController, traficLightEast, "Messages", "Serial Protocol")
@enduml